name 'boxcutter_onepassword'
maintainer 'Boxcutter'
maintainer_email 'noreply@boxcutter.io'
license 'Apache-2.0'
description 'Installs/Configures boxcutter_onepassword'
source_url 'https://github.com/boxcutter/boxcutter-chef-cookbooks/'
version '0.1.0'
