name 'boxcutter_builder'
maintainer 'Boxcutter'
maintainer_email 'noreply@boxcutter.dev'
license 'Apache-2.0'
description 'Installs/Configures boxcutter_builder'
source_url 'https://github.com/boxcutter/boxcutter-chef-cookbooks/'
version '0.1.0'
depends 'boxcutter_docker'
depends 'boxcutter_onepassword'
depends 'boxcutter_can'
depends 'fb_networkd'
