name 'boxcutter_ci_fixes'
maintainer 'Boxcutter'
maintainer_email 'noreply@boxcutter.dev'
license 'Apache-2.0'
description 'Misc fixes to make the CI work'
source_url 'https://github.com/boxcutter/boxcutter-chef-cookbooks/'
version '0.0.1'
supports 'centos'
supports 'debian'
supports 'fedora'
supports 'ubuntu'
depends 'fb_helpers'
