---
driver:
  name: dokken
  privileged: true  # allows systemd services to start
  docker_registry: docker.io
  chef_image: boxcutter/cinc
  # Upstream reusable-kitchen-tests currently using CHEF_VERSION=18.6.14
  # There's no Cinc Client release for this version, so we're using the
  # closest 18.6.x release to that.
  #
  # chef_version: <%= ENV['CHEF_VERSION'] || 'current' %>
  chef_version: 18.6.2

provisioner:
  name: dokken
  product_name: cinc
  chef_binary: /opt/cinc/bin/cinc-client
  chef_license: accept-no-persist
  chef_log_level: <%= ENV['CHEF_LOG_LEVEL'] || 'auto' %>
  client_rb:
    file_staging_uses_destdir: false
    client_fork: false
    force_logger: true
    log_location: /var/log/chef.log
    ohai.optional_plugins:
      - Passwd
    ohai.critical_plugins:
      - Passwd

transport:
  name: dokken

lifecycle:
  post_create:
    - remote: |
        bash -c -x '
          # Force firstboot
          touch /root/firstboot_os
        '

platforms:
  - name: fedora-40
    driver:
      image: boxcutter/dokken-fedora-40
      pid_one_command: /usr/lib/systemd/systemd
      intermediate_instructions:
        # stub out /etc/fstab for fb_fstab
        - RUN touch /etc/fstab
  - name: fedora-41
    driver:
      image: boxcutter/dokken-fedora-41
      pid_one_command: /usr/lib/systemd/systemd
      intermediate_instructions:
        # stub out /etc/fstab for fb_fstab
        - RUN touch /etc/fstab
  - name: centos-stream-9
    driver:
      image: boxcutter/dokken-centos-stream-9
      pid_one_command: /usr/lib/systemd/systemd
      intermediate_instructions:
        # stub out /etc/fstab for fb_fstab
        - RUN touch /etc/fstab
        # enable EPEL (for stuff like hddtemp)
        - RUN rpm -Uvh https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm
  - name: centos-stream-10
    driver:
      image: boxcutter/dokken-centos-stream-10
      pid_one_command: /usr/lib/systemd/systemd
      intermediate_instructions:
        # stub out /etc/fstab for fb_fstab
        - RUN touch /etc/fstab
        # mirrorlist.centos.org doesn't exist anymore, use baseurl
        - RUN sed -i=.bak -e 's/^mirrorlist/#mirrorlist/g' -e 's!^#baseurl=http://mirror.centos.org/$contentdir/$stream!baseurl=https://vault.centos.org/$stream!g' /etc/yum.repos.d/*.repo
        - RUN rm /etc/yum.repos.d/*.bak
        # enable EPEL (for stuff like hddtemp)
        - RUN rpm -Uvh https://dl.fedoraproject.org/pub/epel/epel-release-latest-10.noarch.rpm
  - name: ubuntu-24.04
    driver:
      image: boxcutter/dokken-ubuntu-24.04
      pid_one_command: /bin/systemd
  - name: ubuntu-22.04
    driver:
      image: boxcutter/dokken-ubuntu-22.04
      pid_one_command: /bin/systemd
  - name: debian-12
    driver:
      image: boxcutter/dokken-debian-12
      pid_one_command: /bin/systemd

suites:
  - name: local
    run_list:
      - recipe[boxcutter_ohai]
      - recipe[boxcutter_ci_fixes]
      - recipe[boxcutter_init]
