name 'boxcutter_robot'
maintainer 'Boxcutter'
maintainer_email 'noreply@boxcutter.dev'
license 'Apache-2.0'
description 'Installs/Configures boxcutter_robot'
source_url 'https://github.com/boxcutter/boxcutter-chef-cookbooks/'
version '0.1.0'
depends 'boxcutter_can'
depends 'boxcutter_jfrog'
depends 'boxcutter_nfs'
depends 'boxcutter_podman'
depends 'boxcutter_prometheus'
depends 'boxcutter_ros'
