default_config = value_for_platform(
  'centos' => {
    'default' => {
      'max_connections' => 100,
      'shared_buffers' => '128MB',
      'dynamic_shared_memory_type' => 'posix',
      'max_wal_size' => '1GB',
      'min_wal_size' => '80MB',
      'log_destination' => 'stderr',
      'logging_collector' => 'on',
      'log_directory' => 'log',
      'log_filename' => 'postgresql-%a.log',
      'log_rotation_age' => '1d',
      'log_rotation_size' => 0,
      'log_truncate_on_rotation' => 'on',
      'log_line_prefix' => '%m [%p] ',
      'log_timezone' => 'UTC',
      'datestyle' => 'iso, mdy',
      'timezone' => 'UTC',
      'lc_messages' => 'C.utf8',
      'lc_monetary' => 'C.utf8',
      'lc_numeric' => 'C.utf8',
      'lc_time' => 'C.utf8',
      'default_text_search_config' => 'pg_catalog.english',
    },
  },
  'ubuntu' => {
    'default' => {
      'data_directory' => '/var/lib/postgresql/16/main',
      'hba_file' => '/etc/postgresql/16/main/pg_hba.conf',
      'ident_file' => '/etc/postgresql/16/main/pg_ident.conf',
      'external_pid_file' => '/var/run/postgresql/16-main.pid ',
      'port' => 5432,
      'max_connections' => 100,
      'unix_socket_directories' => '/var/run/postgresql',
      'ssl' => 'on',
      'ssl_cert_file' => '/etc/ssl/certs/ssl-cert-snakeoil.pem',
      'ssl_key_file' => '/etc/ssl/private/ssl-cert-snakeoil.key',
      'shared_buffers' => '128MB',
      'dynamic_shared_memory_type' => 'posix',
      'max_wal_size' => '1GB',
      'min_wal_size' => '80MB',
      'log_line_prefix' => '%m [%p] %q%u@%d ',
      'log_timezone' => 'Etc/UTC',
      'cluster_name' => '16/main',
      'datestyle' => 'iso, mdy',
      'timezone' => 'Etc/UTC',
      'lc_messages' => 'C.UTF-8',
      'lc_monetary' => 'C.UTF-8',
      'lc_numeric' => 'C.UTF-8',
      'lc_time' => 'C.UTF-8',
      'default_text_search_config' => 'pg_catalog.english',
      'include_dir' => 'conf.d',
    },
  },
)

default['boxcutter_postgresql'] = {
  'server' => {
    'enable' => true,
    'config' => default_config,
    'pg_hba' => {
      :hosts => [
        { :type => 'local', :database => 'all', :user => 'postgres', :method => 'peer' },
        { :type => 'local', :database => 'all', :user => 'all', :method => 'peer' },
        { :type => 'host', :database => 'all', :user => 'all', :address => '127.0.0.1/32', :method => 'scram-sha-256' },
        { :type => 'host', :database => 'all', :user => 'all', :address => '::1/128', :method => 'scram-sha-256' },
        { :type => 'local', :database => 'replication', :user => 'all', :method => 'peer' },
        { :type => 'host', :database => 'replication', :user => 'all', :address => '127.0.0.1/32', :method => 'scram-sha-256' },
        { :type => 'host', :database => 'replication', :user => 'all', :address => '::1/128', :method => 'scram-sha-256' },
      ],
    },
  },
}
