---
driver:
  name: dokken
  privileged: true  # allows systemd services to start
  docker_registry: docker.io
  chef_image: boxcutter/cinc
  chef_version: <%= ENV['CHEF_VERSION'] || 'current' %>

provisioner:
  name: dokken
  product_name: cinc
  chef_binary: /opt/cinc/bin/cinc-client
  chef_license: accept-no-persist
  chef_log_level: <%= ENV['CHEF_LOG_LEVEL'] || 'auto' %>
  client_rb:
    # Needed to avoid apply2file error on intel for mac
    file_backup_path: nil
    # Passwd plugin is needed to use the fb_users cookbook
    ohai.optional_plugins:
      - Passwd
    ohai.critical_plugins:
      - Passwd

transport:
  name: dokken

lifecycle:
  post_create:
    - remote: |
        bash -c -x '
          # Force firstboot
          touch /root/firstboot_os
        '

verifier:
  name: inspec

platforms:
  # @see https://github.com/chef-cookbooks/testing_examples/blob/main/kitchen.dokken.yml
  # @see https://hub.docker.com/u/dokken
  - name: ubuntu-22.04
    driver:
      image: boxcutter/dokken-ubuntu-22.04
      pid_one_command: /bin/systemd

  - name: ubuntu-24.04
    driver:
      image: boxcutter/dokken-ubuntu-24.04
      pid_one_command: /bin/systemd
      ports:
        - '9090:9090' # prometheus
        - '9091:9091' # pushgateway
        - '9093:9093' # alertmanager
        - '9100:9100' # node_exporter
        - '9115:9115' # blackbox_exporter
        - '9116:9116' # snmp_exporter
        - '9121:9121' # redis_exporter
        - '9187:9187' # postgres_exporter
        - '9835:9835' # nvidia_gpu_exporter
        - '3000:3000' # grafana

  - name: centos-stream-9
    driver:
      image: boxcutter/dokken-centos-stream-9
      pid_one_command: /usr/lib/systemd/systemd
      intermediate_instructions:
        # stub out /etc/fstab for fb_fstab
        - RUN touch /etc/fstab
        # enable EPEL (for stuff like hddtemp)
        - RUN rpm -Uvh https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm

suites:
  - name: default
    # run_list set in Policyfile.rb, this does nothing
    # run_list:
    #   - recipe[boxcutter_ohai]
    #   - recipe[boxcutter_init]
    #   - recipe[boxcutter_prometheus::default]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:

  - name: prometheus
    named_run_list: boxcutter_prometheus_test_prometheus
    verifier:
      inspec_tests:
        - test/integration/prometheus
    attributes:

  - name: alertmanager
    named_run_list: boxcutter_prometheus_test_alertmanager
    verifier:
      inspec_tests:
        - test/integration/alertmanager
    attributes:

  - name: pushgateway
    named_run_list: boxcutter_prometheus_test_pushgateway
    verifier:
      inspec_tests:
        - test/integration/pushgateway
    attributes:

  - name: blackbox_exporter
    named_run_list: boxcutter_prometheus_test_blackbox_exporter
    verifier:
      inspec_tests:
        - test/integration/blackbox_exporter
    attributes:

  - name: node_exporter
    named_run_list: boxcutter_prometheus_test_node_exporter
    verifier:
      inspec_tests:
        - test/integration/node_exporter
    attributes:

  - name: postgres_exporter
    named_run_list: boxcutter_prometheus_test_postgres_exporter
    verifier:
      inspec_tests:
        - test/integration/postgres_exporter
    attributes:

  - name: redis_exporter
    named_run_list: boxcutter_prometheus_test_redis_exporter
    verifier:
      inspec_tests:
        - test/integration/redis_exporter
    attributes:

  - name: nvidia_gpu_exporter
    named_run_list: boxcutter_prometheus_test_nvidia_gpu_exporter
    verifier:
      inspec_tests:
        - test/integration/nvidia_gpu_exporter
    attributes:

  - name: snmp_exporter
    named_run_list: boxcutter_prometheus_test_snmp_exporter
    verifier:
      inspec_tests:
        - test/integration/snmp_exporter
    attributes:
