name 'boxcutter_netbox'
maintainer 'Boxcutter'
maintainer_email 'noreply@boxcutter.dev'
license 'Apache-2.0'
description 'Installs/Configures boxcutter_netbox'
source_url 'https://github.com/boxcutter/boxcutter-chef-cookbooks/'
version '0.1.0'
depends 'boxcutter_postgresql'
depends 'boxcutter_redis'
depends 'boxcutter_python'
