name 'boxcutter_site_settings'
maintainer 'Boxcutter'
maintainer_email 'noreply@boxcutter.dev'
license 'Apache-2.0'
description 'Installs/Configures boxcutter_site_settings'
source_url 'https://github.com/boxcutter/boxcutter-chef-cookbooks/'
version '0.1.0'
depends 'boxcutter_users'
depends 'fb_helpers'
