name: Continuous Integration
on:
  push:
    branches: [main]
  pull_request:
jobs:
  kitchen:
    strategy:
      fail-fast: false
      matrix:
        os:
          - centos-7
          - ubuntu-2004
          - ubuntu-2204
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Checkout chef-cookbooks repository
      uses: actions/checkout@v3
      with:
        repository: boxcutter/chef-cookbooks
        path: chef-cookbooks
    - name: Install Chef
      uses: actionshub/chef-install@1.1.0
      with:
        omnitruckUrl: omnitruck.cinc.sh
        project: chef-workstation
        version: 20.11.180
    - name: Run Kitchen
      uses: actionshub/test-kitchen@2.0.0
      with:
        suite: default
        os: ${{ matrix.os }}
      env:
        CHEF_LICENSE: accept-no-persist
        CHEF_VERSION: 14.15.6

